import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Mail, Lock, Eye, EyeOff, Sparkles, ArrowRight, TrendingUp } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

const InfluencerLogin = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const { user, influencerLogin, isAuthenticated } = useAuth();
  const navigate = useNavigate();

  // If already logged in as approved Influencer, redirect directly to /influencer
  useEffect(() => {
    if (isAuthenticated && (user?.role === 'influencer' || user?.influencerStatus === 'approved')) {
      navigate('/influencer', { replace: true });
    }
  }, [isAuthenticated, user, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!email || !password) {
      setError('Please enter both creator email and password.');
      return;
    }

    setLoading(true);
    try {
      await influencerLogin(email, password);
      setLoading(false);
      navigate('/influencer', { replace: true });
    } catch (err) {
      setLoading(false);
      setError(err.message || 'Invalid Influencer Credentials.');
    }
  };

  return (
    <div className="min-h-screen pt-24 pb-16 flex items-center justify-center bg-[#0b132b] px-4 relative overflow-hidden">
      {/* Background Orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-4xl w-full bg-slate-900 rounded-3xl shadow-2xl overflow-hidden border border-slate-800 grid grid-cols-1 md:grid-cols-2 relative z-10">
        {/* Left Side: Influencer Branding */}
        <div className="relative hidden md:flex flex-col justify-between p-10 bg-gradient-to-b from-slate-900 via-slate-900 to-emerald-950 text-white border-r border-slate-800">
          <div>
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-xs font-black text-emerald-400 mb-6">
              <Sparkles size={16} /> Partner & Influencer Portal
            </div>
            <h2 className="text-3xl font-black leading-tight mb-4 text-white">
              Monetize Your Travel Audience with WanderLuxe
            </h2>
            <p className="text-slate-300 text-xs md:text-sm leading-relaxed font-medium">
              Generate custom coupon codes, track real-time bookings generated by your followers, and earn up to 10% commission on gross sales.
            </p>
          </div>

          <div className="pt-8 border-t border-slate-800 space-y-3">
            <div className="flex items-center gap-3 text-xs font-bold text-emerald-400">
              <TrendingUp size={18} /> Over ₹48.5k Earned by Top Creators
            </div>
            <div className="text-[11px] text-slate-400 font-mono">
              Admin-verified creators enjoy direct instant login & dashboard access.
            </div>
          </div>
        </div>

        {/* Right Side: Login Form */}
        <div className="p-8 md:p-12 flex flex-col justify-center text-white">
          <div className="mb-6">
            <span className="text-xs font-black text-emerald-400 uppercase tracking-wider block mb-1">
              Verified Creator Login
            </span>
            <h1 className="text-2xl md:text-3xl font-black text-white">Influencer Control Panel</h1>
            <p className="text-slate-400 text-xs mt-1">Sign in with your approved creator account</p>
          </div>

          {error && (
            <div className="mb-6 p-4 rounded-2xl bg-rose-950/60 border border-rose-800 text-rose-300 text-xs font-bold leading-relaxed">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-300 mb-1.5">
                Creator Email Address
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18} />
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="creator@yourdomain.com"
                  className="w-full pl-11 pr-4 py-3 bg-slate-800/80 border border-slate-700 rounded-2xl focus:outline-none focus:border-emerald-500 text-white text-xs font-bold"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-300 mb-1.5">
                Password
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full pl-11 pr-12 py-3 bg-slate-800/80 border border-slate-700 rounded-2xl focus:outline-none focus:border-emerald-500 text-white text-xs font-bold"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white"
                >
                  {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-4 bg-emerald-500 text-white rounded-2xl font-black text-sm hover:bg-emerald-600 transition-all shadow-xl shadow-emerald-500/25 flex items-center justify-center gap-2 mt-2"
            >
              {loading ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <>
                  Access Influencer Dashboard <ArrowRight size={18} />
                </>
              )}
            </button>
          </form>

          <p className="mt-6 text-center text-xs text-slate-400">
            Not an approved creator yet?{' '}
            <Link to="/influencer/signup" className="text-emerald-400 font-extrabold hover:underline">
              Apply to Become an Influencer &rarr;
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default InfluencerLogin;
